workspace:
  base: /srv/drone-demo
  path: .

kind: pipeline
name: demo

steps: 
  - name: greeting
    image: hello-world

  - name: build # 尝试编译go应用
    image: golang:1.11.4
    commands:
      - pwd
      - go version
      - go build .
      - go test demo/util

  - name: push-docker-staging  # 测试镜像构建
    image: plugins/docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    settings:
      # cache_from: golang:1.11.4,haobird/demo
      repo: haobird/demo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:  
        - staging
        - sha_${DRONE_COMMIT_SHA} 
    when:  
      branch: master  
      event: push
    
#   - name: deploy
#     image: appleboy/drone-ssh
#     pull: true
#     settings:
#       host: 116.62.128.252
#       user: root
#       key:
#         from_secret: deploy_key
#       script:
#         - cd /data/
#         - mkdir app22/
#         - cd /data/app22
#         - docker rmi -f haobird/demo
#         - echo "login docker"
# #        - docker login --username ${DOCKER_USER} --password ${DOCKER_SEC}
#         - echo "login success, pulling..."
#         - docker pull haobird/demo:latest
#         - echo "image running"
#         - docker run -p 8088:8088 -d haobird/demo
#         - echo "run success"


# volumes:  
#   - name: cache  
#     host:  
#       path: /tmp/cache
